### ISSUE TITLE
Cart getting empty after payment fail

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#11]
1. Sign In using authorized credentials.
2. Added the products to the cart.
3. Proceed to checkout then pick the payment method.
4. Due to technical issues payment was not done.
5. Once back to website page from payment page showing " Payment fail Purchase again" but the cart is empty. 

If user want to go for purchase again the cart should have the same products.

**Comment by RaviTeja-S7412** [comment]
done
