### ISSUE TITLE
Add to cart- Functionality

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#18]
"Products page cart symbol on the product thumbnail is not checking stock availability.

(""Adding product to cart using cart symbol on product, product get added to cart depends
 on clicks even if there is no stock available.( If user click the cart symbol 5 times the
 product get added to the cart 5 times, even if no of products available  1 too)"")"

"Restrict the user to add more products to the cart than 
available stock with an appropriate error message."

![Cart stock error](https://user-images.githubusercontent.com/18025417/90535967-13ffd280-e199-11ea-9e81-52cab62dc512.png)

**Comment by RaviTeja-S7412** [comment]
done
