### ISSUE TITLE
What is meant by Delivery Status and Order Status?		- From Client 	

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#2]
![image](https://user-images.githubusercontent.com/18025417/90485891-c7df6e80-e155-11ea-86f7-f95bd5de03bb.png)

**Comment by veda2wratha** [comment]
Diliver status means .. delivery of that product

Order status means .. complete order status.

Example : if order confirmed then order status will be in confirm. If Cancelled it will be cancelled.. etc

Delivery status should be, out for delivery, diliverd, not delivered etc..

**Comment by Sumana12** [comment]
Cleared
