### ISSUE TITLE
UI-Order History Link

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#28]
**Orders History**  should be somewhere at the top of the page. Preceding Wish list.  

![image](https://user-images.githubusercontent.com/18025417/90636443-3997e500-e248-11ea-9751-5f8fbc0bb801.png)

**Comment by RaviTeja-S7412** [comment]
as we discussed you said i will suggest the location where we have to place the order history link

**Comment by Sumana12** [comment]
Can place beside Wish list as My Orders.

**Comment by Sumana12** [comment]
Done
