### ISSUE TITLE
Wishlist -Functionality 

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#30]
"Once a product is added to the Wish list the heart symbol turns red but clicking on it again does not 
 remove it from the Wish list at product listing page and Product details page."

Once you click on and again click on it should off.

**Comment by RaviTeja-S7412** [comment]
done

**Comment by Sumana12** [comment]
tested in 3 different browsers changes not reflected . Reopening this issue.

**Comment by Sumana12** [comment]
Done
