### ISSUE TITLE
Cart Functionality

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#33]
Cart should save to database.

Ex: I have added 2 products to cart in my account. 
Once I login to my account in another browser the cart is empty.

**Comment by RaviTeja-S7412** [comment]
here we are using cart library total products will be stored in sessions, that's why  we cannot see the same in another browser

**Comment by Sumana12** [comment]
Veda confirm on this so that I can close this issue.

**Comment by veda2wratha** [comment]
Ok ravi but should not be like that.. if I add in my account after login it should save in database with user id... Then show the list of added products based on the login.. 


For example I will add some products from my pc and next opening site in mobile .. it should show all added products.

We need to fix this.

**Comment by Sumana12** [comment]
Done
