### ISSUE TITLE
Billing address and delivery address should be present in "Order Information"(customer invoice)		-Client 						

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#44]
Billing address and delivery address should be present in   "Order Information"(customer invoice)
--

**Comment by RaviTeja-S7412** [comment]
please mention the page where it should show

**Comment by Sumana12** [comment]
Customer invoice means order Details page.

![image](https://user-images.githubusercontent.com/18025417/91422904-6e71f080-e875-11ea-93f6-44707941eb68.png)

**Comment by Sumana12** [comment]
We are considering billing and Delivery address are same here.
