### ISSUE TITLE
Tracking status should be shown immediately after clicking on tracking ID, - Client				

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#45]
Tracking status should be shown immediately after clicking on   tracking ID,
--

**Comment by veda2wratha** [comment]
This is also not a question.. they saying functionality. 

@RaviTeja-S7412 pls check

**Comment by Sumana12** [comment]
need to implement Tracking status.

![image](https://user-images.githubusercontent.com/18025417/91423544-52228380-e876-11ea-856c-1d129d1fa5c2.png)
