### ISSUE TITLE
Tracking Alert	

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#46]
Tracking alerts of that particular customer should be updated   through mail.
--

**Comment by veda2wratha** [comment]
Yes .. will send mail once tracking id is assigned.

@RaviTeja-S7412 9/pls check this.

@Sumana12 check whether we are sending mail or not

**Comment by Sumana12** [comment]
As per today's discussion Ravi said that we need to get email design for this.

**Comment by Sumana12** [comment]
we are getting email but click on or Order details to know order status taking to prasannalakshmisilks site there orders details are missed.
Missed order details at User dashboard
![image](https://user-images.githubusercontent.com/18025417/93882419-d6ddb180-fcfd-11ea-956f-ff062e188ae9.png)


![image](https://user-images.githubusercontent.com/18025417/94008064-fccb8a80-fdbf-11ea-8d92-dfa620423882.png)
