### ISSUE TITLE
Shipping Address - Validation

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#59]
Unable to move further, 

![image](https://user-images.githubusercontent.com/18025417/90984698-45f7a700-e594-11ea-8c85-c9681e0e971f.png)

**Comment by RaviTeja-S7412** [comment]
here we are accepting only a-z A-Z characters

**Comment by Sumana12** [comment]
If it will be KPHB 2nd phase?

**Comment by Sumana12** [comment]
Done
