### ISSUE TITLE
Recently viewed  Products unchange

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#83]
Recently Viewed products are showing same for different logins.
Showing same products at recently viewed for newly signed up user too

**Comment by RaviTeja-S7412** [comment]
it will work on ip based not related to user accounts.

**Comment by Sumana12** [comment]
Recently viewed products shouldn't show repeatedly.
![image](https://user-images.githubusercontent.com/18025417/92748893-399c8800-f3a3-11ea-8805-970bd8c1cf09.png)

**Comment by Sumana12** [comment]
Recently views option removed ?

**Comment by Sumana12** [comment]
Done
