### ISSUE TITLE
Prodcut Already Added to Cart message

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#87]
1. Added product to cart from products listing page using cart symbol. Once again I tried to add the same product to cart by clicking cart symbol at products listing page throwing error " Already Added to the cart" . It's right scenario.
2. Once I go to another page and back to the product listing page and tried to add the same product to cart again using cart symbol on the product now not throwing error message that product already added to the cart.

**Comment by RaviTeja-S7412** [comment]
there we have changed the icon of that product that indicating product is already to cart with check symbol.

**Comment by Sumana12** [comment]
Done
