### ISSUE TITLE
Shipping Address Format - Client

### ISSUE THREAD

**Issue by Sumana12** [veda2wratha/PLS-Web#9]
First Name |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

Last Name |   |   |   |   |   |   |   |   |  

H/No |   |   |   |   |   |   |   |   |   |  

Land mark |   |   |   |   |   |   |   |   |  

pin/Zip code |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

  city name |   |   |   |   |   |   |   |   |   |  
 
state name |   |   |   |   |   |   |   |   |  
 
country name |   |   |   |   |   |   |   |   |  

Phone number |   |   |   |   |   |   |   |   |  

  |   | country | phone number |   |   |   |   |   |  

  |   | code |   |   |   |   |   |   |   |  

Note:1.Only   Landmark is optional.Remaining all are mandatory. |   |   |   |   |  
2.Depending   on country name and pin code shipping cost should be added.Address should be   accepting only if it is valid

**Comment by RaviTeja-S7412** [comment]
done please check and confirm

**Comment by RaviTeja-S7412** [comment]
done
